services:
  # Excalidraw
  excalidraw-backend:
    image: jitsi/excalidraw-backend:latest
    restart: always
    # ports:
    #   - "8080:80"

  # Jitsi Web UI
  web:
    image: jitsi/web:stable-10133
    restart: always
    # ports:
    #   - "80:80"
    #   - "443:443"
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      # - ENABLE_AUTH=1 # Used for JWT Auth
      # - ENABLE_GUESTS=0 # Used for JWT Auth
      - DEFAULT_LANGUAGE=en-US
      - ENABLE_XMPP_WEBSOCKET=1
      - PUBLIC_URL=https://jitsi.toluolatubosun.com
    volumes:
      - ./web/config.js:/config/config.js:ro  # Mount the custom config
      - ./web/nginx.conf:/config/nginx/meet.conf:ro  # Mount the custom Nginx config
      - ./web/interface_config.js:/config/interface_config.js:ro # Mount the custom interface config
    networks:
      - jitsi

  # Prosody (XMPP Server)
  prosody:
    image: jitsi/prosody:stable-10133
    restart: always
    ports:
      - "5280:5280"
      - "5281:5281"
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      # - ENABLE_AUTH=1 # Used for JWT Auth
      # - ENABLE_GUESTS=0 # Used for JWT Auth
      - JVB_AUTH_USER=jvb
      # - AUTH_TYPE=jwt # Used for JWT Auth
      # - JWT_AUTH_TYPE=token # Used for JWT Auth
      # - JWT_APP_ID=jitsi_toluolatubosun_app # Used for JWT Auth
      # - JWT_APP_SECRET=RandomSecret1 # Used for JWT Auth
      - ENABLE_XMPP_WEBSOCKET=1
      - JVB_AUTH_PASSWORD=RandomPassword2
      - JICOFO_AUTH_PASSWORD=RandomPassword1
    networks:
      - jitsi

  # Jicofo (Conference Focus)
  jicofo:
    image: jitsi/jicofo:stable-10133
    restart: always
    environment:
      - ENABLE_AUTH=0
      # - ENABLE_AUTH=1 # Used for JWT Auth
      # - AUTH_TYPE=jwt # Used for JWT Auth
      - XMPP_SERVER=prosody
      - JICOFO_AUTH_PASSWORD=RandomPassword1
    networks:
      - jitsi

  # JVB (Video Bridge)
  jvb:
    image: jitsi/jvb:stable-10133
    restart: always
    ports:
      - "10000:10000/udp"
    environment:
      - ENABLE_AUTH=0
      # - ENABLE_AUTH=1 # Used for JWT Auth
      # - AUTH_TYPE=jwt # Used for JWT Auth
      - JVB_AUTH_USER=jvb
      - XMPP_SERVER=prosody
      - JVB_STUN_SERVERS=stun.l.google.com:19302
      - JVB_AUTH_PASSWORD=RandomPassword2
    networks:
      - jitsi

networks:
  jitsi:
    driver: bridge

