services:
  # Excalidraw
  excalidraw-backend:
    image: jitsi/excalidraw-backend:latest
    restart: always
    # ports:
    #   - "8080:80"

  # Jitsi Web UI
  web:
    image: jitsi/web:stable-10133
    restart: always
    # ports:
    #   - "80:80"
    #   - "443:443"
    environment:
      - PUBLIC_URL=https://jitsi.toluolatubosun.com
      - ENABLE_XMPP_WEBSOCKET=1
      - ENABLE_LOBBY=0
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - LOGO_URL=https://toluolatubosun.com/images/logo.png
      - BRANDING_NAME="King Meet"
      - XMPP_SERVER=prosody
      - DEFAULT_LANGUAGE=en-US
      - LANG_DETECTION=false
    volumes:
      - ./config.js:/config/config.js:ro  # Mount the custom config
      - ./nginx.conf:/config/nginx/meet.conf:ro  # Mount the custom Nginx config
      - ./interface_config.js:/config/interface_config.js:ro # Mount the custom interface config
    networks:
      - jitsi

  # Prosody (XMPP Server)
  prosody:
    image: jitsi/prosody:stable-10133
    restart: always
    ports:
      - "5280:5280"
      - "5281:5281"
    environment:
      - ENABLE_AUTH=0
      - ENABLE_LOBBY=0
      - ENABLE_GUESTS=1
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=RandomPassword1
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=RandomPassword2
      - ENABLE_XMPP_WEBSOCKET=1
      - ENABLE_XMPP_SMACKS=1
    networks:
      - jitsi

  # Jicofo (Conference Focus)
  jicofo:
    image: jitsi/jicofo:stable-10133
    restart: always
    environment:
      - ENABLE_AUTH=0
      - ENABLE_LOBBY=0
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=RandomPassword1
      - XMPP_SERVER=prosody
    networks:
      - jitsi

  # JVB (Video Bridge)
  jvb:
    image: jitsi/jvb:stable-10133
    restart: always
    ports:
      - "10000:10000/udp"
    environment:
      - JVB_STUN_SERVERS=stun.l.google.com:19302
      - XMPP_SERVER=prosody
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=RandomPassword2
    networks:
      - jitsi

networks:
  jitsi:
    driver: bridge

